<a href="https://colab.research.google.com/github/aman40399/AIML/blob/main/numpy%26array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy
NumPy (Numerical Python) is an open source Python library . The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional ndarray, and a large library of functions that operate efficiently on these data structures

python arrays /containers are heterogenious mean they can store any int var char any type of variable but numoy shines in homogenous data to be processed on the cpu

some restrictions
Most NumPy arrays have some restrictions. For instance:

    All elements of the array must be of the same type of data.

    Once created, the total size of the array can’t change.

    The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.



# why numpy ?
NumPy is a fundamental Python library designed for efficient numerical and scientific computing, especially when working with large datasets or performing complex mathematical operations. Here’s why we use NumPy:
Key Reasons to Use NumPy

1. Fast and Efficient Array Operations

    NumPy provides an array object called ndarray that is much faster than Python’s built-in lists for numerical operations. This speed comes from the fact that NumPy arrays are stored in contiguous memory and leverage optimized C and C++ code under the hood, making operations up to 50x faster than native Python lists

    .

2. Powerful Mathematical Functions

    NumPy comes with a wide range of mathematical functions, including linear algebra, Fourier transforms, random number generation, and statistical operations, all optimized for use with arrays

    .

3. Vectorization and Readable Code

    Operations in NumPy are vectorized, meaning you can perform element-wise operations on entire arrays without explicit loops. This not only improves speed but also makes code cleaner and closer to standard mathematical notation

    .

4. Multidimensional Arrays

    NumPy supports n-dimensional arrays (tensors), making it easy to work with matrices and higher-dimensional data, which is essential for scientific computing, machine learning, and data analysis

.

In [2]:
import numpy as np

In [3]:
#manual array genration
a=np.array([[111],[222],[333],[444]])
a


array([[111],
       [222],
       [333],
       [444]])

#  Array Attributes

this section covers the ndim, shape, size, and dtype attributes of an array.

to check number of dimesion present in array

In [4]:
a.ndim

2

inoder to check the shape of your array : or : rows & columns

In [5]:
a.shape  #4 rows, 1 column

(4, 1)

In [6]:
# len of give result bu a.shape which is (5,1) is same as a.ndim
len(a.shape)==a.ndim





True

tpy

# onlie last line code output is shown inside , the jupiter note book so inorder to show all the code u can use container like tuple below 

the fixed, total number of elements in array is contained in the size attribute

In [7]:
a.size #total number of elements in the array # 4 rows * 1 column = 4 elements
a.dtype #data type of the array elements, here it is int64
a.itemsize #size of each element in bytes, here it is 8 bytes for int64
a.nbytes #total number of bytes used by the array, here it is 32 bytes (4 elements * 8 bytes each)
(a.size, a.dtype, a.itemsize, a.nbytes)  #tuple of size, dtype, itemsize, nbytes

(4, dtype('int64'), 8, 32)

inorder to find the type of data type in narray

In [8]:
a.dtype

# NOTE
# dtype can also be used  to specify value of your array
np.array([1,2,3,4],dtype=float)

array([1., 2., 3., 4.])

to find the number of elements inside the narray

to find the

In [9]:
a.size

4

# How to create a basic array

This section covers np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()

Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s

In [10]:
# auotgenration
np.zeros(2)

array([0., 0.])

In [11]:
# filled with ones (autogenration)
np.ones(3)

array([1., 1., 1.])

In [12]:
# USING EMPTY (autogenration)
#empty is used to create an narray of random value existing in memonry only reason we use this is to make an narray faster then any bc you dont have to genrate the values , it not empty as name suggested
np.empty(2)

array([0., 0.])

In [13]:
# can create an array with a range of elements (autogenration):
print(np.arange(12))


# also can define the array autogenrated  by using parameters
#np,arange(first number, last number, and the step size.)
np.arange(2,9,2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([2, 4, 6, 8])

In [14]:
#linespace : use to create a linearly spaced array (autogenration)
np.linspace(0,100,101)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100.])

# adding removing sorting elements

In [15]:
# np.argsort()

# Returns indices that would sort an array.
# Example:

arr = np.array([10, 5, 30])
indices = np.argsort(arr)
# Output: [1, 0, 2]
# Explanation: arr[1]=5, arr[0]=10, arr[2]=30 → sorted order.

# Use when: You want to sort indirectly (e.g., reorder another array the same way).





In [16]:
# 🔠 np.lexsort()

# Performs a stable sort using multiple keys (from last to first key).
# Example:

names = np.array(['John', 'Jane', 'John', 'Jane'])
ages = np.array([25, 30, 20, 25])
indices = np.lexsort((ages, names))
print(indices)
# Sort by name, then age.
# Use when: You need multi-level sorting, like by name and then age.

[3 1 2 0]


In [17]:
# 🔍 np.searchsorted()

# Finds indices where elements should be inserted in a sorted array to maintain order.
# Example:

arr = np.array([10, 20, 30, 40])
np.searchsorted(arr, 25)
# Output: 2 (25 should go before 30)

# Use when: You're inserting into a sorted array or doing binary search-like tasks.

np.int64(2)

In [18]:

# ⚡ np.partition()

# Performs a partial sort: places the kth smallest item in its correct position, with smaller ones before and larger ones after, but doesn't fully sort.
# Example:

arr = np.array([7, 2, 9, 1, 6])
np.partition(arr, 2)
# Output: [2, 1, 6, 9, 7] (3 smallest elements on left)

array([1, 2, 6, 7, 9])

# 3. SLICING NDARRAY 

In [ ]:
# slicing an ndarray 
arr = np.array([1, 2, 3, 4, 5, 6, 7])


# removing an element from a NumPy array at specific index
# NumPy arrays do not have a pop method like Python lists.
# To remove an element at index 1, use np.delete:
arr = np.delete(arr, 1) # creates a new array without the element the selected index
print(arr)

# slicing an ndarray (also works with lists in python)
print(arr[1:4])  # prints elements from index 1 to 3


print(arr[1:])  # prints elements from index 1 to the end
print(arr[:4])  # prints elements from the start to index 3
print(arr[:])   # prints the entire array
print(arr[::2])  # prints every second element (slicing with step)
# slicing with negative indices
print(arr[-3:])  # prints the last 3 elements
print(arr[:-3])  # prints all elements except the last 3
print(arr[-4:-1])  # prints elements from index -4 to -2
print(arr[-4:])  # prints elements from index -4 to the end
print(arr[-4:-1])  # prints elements from index -4 to -2 


[1 3 4 5 6 7]
[3 4 5]
[3 4 5 6 7]
[1 3 4 5]
[1 3 4 5 6 7]
[1 4 6]
[5 6 7]
[1 3 4]
[4 5 6]
[4 5 6 7]
[4 5 6]


# 4.DATA TYPES IN PYTHON VS NUMPY 

## PYTHON
    strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
    integer - used to represent integer numbers. e.g. -1, -2, -3
    float - used to represent real numbers. e.g. 1.2, 42.42
    boolean - used to represent True or False.
    complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

## IN NUMPY 

    i - integer
    b - boolean
    u - unsigned integer
    f - float
    c - complex float
    m - timedelta
    M - datetime
    O - object
    S - string
    U - unicode string
    V - fixed chunk of memory for other type ( void )


In [63]:
#checking data type of an array
arr=np.array([1, 2, 3, 4, 5])

print(arr.dtype)  # prints the data type of the array elements

# changing data type of an array
arr_float = arr.astype('f')  # converts the array to float type
print(arr_float.dtype)  # prints the new data type of the array elements
# changing data type of an array to string
arr_str = arr.astype('S')  # converts the array to string type
print(arr_str.dtype)  # prints the new data type of the array elements : <U21

#creating an array with defined data type
arr_int =np.array([1,2,3,4,5],dtype=int)  # creates an array with integer data type
print(arr_int.dtype)  # prints the data type of the array elements : int64


# can also set size of the data type
#Create an array with data type 4 bytes integer:
arr_float32 = np.array([1, 2, 3, 4,5],dtype='i4') 

int64
float32
|S21
int64


## The Difference Between Copy and View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [66]:
arr =np.array([1, 2, 3, 4, 5])
x=arr.copy()

x[0]=0
print(x)
print(arr)  


# view of an array
y=arr.view()  # creates a view of the original array
y[0]=0  # modifies the first element of the view
print(y)
print(arr)

[0 2 3 4 5]
[1 2 3 4 5]
[0 2 3 4 5]
[0 2 3 4 5]


# shape of ndarray 
Shape of an Array

The shape of an array is the number of elements in each dimension.
ex if array is [1,2,3]
               [4,5,6,7]
the result of shape : (3,4)  : first column have 3 elements and second column have 4 elements 

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)
print(arr.ndim) # prints the number of dimensions of the array

#creating an array with predefined shape

arr = np.array([1, 2, 3, 4], ndmin=4)

print(arr)
print(arr.shape)  # prints the shape of the array


# question comes is why [[[[1 2 3 4]]]] is printed
# because ndmin=4 means the array will have 4 dimensions, so it adds extra dimensions around the original array
# If any dimension had a size 0, it would mean that the array contains no data along that axis — i.e., it's empty. But in your case, the array clearly contains data: [1, 2, 3, 4].
#     ndmin=5 → force 5 dimensions
#     Original data shape = (4,)
#     Added 4 singleton dimensions to the left → (1, 1, 1, 1, 4)



(2, 4)
2
[[[[1 2 3 4]]]]
(1, 1, 1, 4)


# RESHAPING AN ARRAY 
1D-2D
Reshaping arrays

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [97]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
reshaped_arr = arr.reshape(4 , 3)  # reshapes the array to 4 rows and 3 columns  
print(reshaped_arr)
print("Shape of reshaped array:", reshaped_arr.shape)
print("Number of dimensions of the reshaped array:", reshaped_arr.ndim)
reshaped_arr= arr.reshape(2,3,2)  
print("3d reshaped array:")
print(reshaped_arr)
print("Shape of 3d reshaped array:", reshaped_arr.shape)
print("Number of dimensions of the 3d reshaped array:", reshaped_arr.ndim)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape of reshaped array: (4, 3)
Number of dimensions of the reshaped array: 2
3d reshaped array:
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Shape of 3d reshaped array: (2, 3, 2)
Number of dimensions of the 3d reshaped array: 3
