<a href="https://colab.research.google.com/github/aman40399/AIML/blob/main/numpy%26array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy
NumPy (Numerical Python) is an open source Python library . The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional ndarray, and a large library of functions that operate efficiently on these data structures

python arrays /containers are heterogenious mean they can store any int var char any type of variable but numoy shines in homogenous data to be processed on the cpu

some restrictions
Most NumPy arrays have some restrictions. For instance:

    All elements of the array must be of the same type of data.

    Once created, the total size of the array can’t change.

    The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.



In [ ]:
import numpy as np

In [ ]:
#manual array genration
a=np.array([[111],[222],[333],[444]])
a


array([[111],
       [222],
       [333],
       [444]])

#  Array Attributes

his section covers the ndim, shape, size, and dtype attributes of an array.

to check number of dimesion present in array

In [ ]:
a.ndim

2

inoder to check the shape of your array : or : rows & columns

In [ ]:
a.shape

(4, 1)

In [ ]:
# len of give result bu a.shape which is (5,1) is same as a.ndim
len(a.shape)==a.ndim





True

he fixed, total number of elements in array is contained in the size attribute

In [ ]:
a.size

4

inorder to find the type of data type in narray

In [ ]:
a.dtype

# NOTE
# dtype can also be used  to specify value of your array
np.array([1,2,3,4],dtype=float)

array([1., 2., 3., 4.])

to find the number of elements inside the narray

to find the

In [ ]:
a.size

5

# How to create a basic array

This section covers np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()

Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s

In [ ]:
# auotgenration
np.zeros(2)

array([0., 0.])

In [ ]:
# filled with ones (autogenration)
np.ones(3)

array([1., 1., 1.])

In [ ]:
# USING EMPTY (autogenration)
#empty is used to create an narray of random value existing in memonry only reason we use this is to make an narray faster then any bc you dont have to genrate the values , it not empty as name suggested
np.empty(2)

array([1., 1.])

In [ ]:
# can create an array with a range of elements (autogenration):
np.arange(12)


# also can define the array autogenrated  by using parameters
#np,arange(first number, last number, and the step size.)
np.arange(2,9,2)

array([2, 4, 6, 8])

In [ ]:
#linespace : use to create a linearly spaced array (autogenration)
np.linspace(0,100,101)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100.])

# adding removing sorting elements

In [ ]:
# np.argsort()

# Returns indices that would sort an array.
# Example:

arr = np.array([10, 5, 30])
indices = np.argsort(arr)
# Output: [1, 0, 2]
# Explanation: arr[1]=5, arr[0]=10, arr[2]=30 → sorted order.

# Use when: You want to sort indirectly (e.g., reorder another array the same way).





array([1, 2, 6, 7, 9])

In [ ]:
# 🔠 np.lexsort()

# Performs a stable sort using multiple keys (from last to first key).
# Example:

names = np.array(['John', 'Jane', 'John', 'Jane'])
ages = np.array([25, 30, 20, 25])
indices = np.lexsort((ages, names))
# Sort by name, then age.
# Use when: You need multi-level sorting, like by name and then age.

In [ ]:
# 🔍 np.searchsorted()

# Finds indices where elements should be inserted in a sorted array to maintain order.
# Example:

arr = np.array([10, 20, 30, 40])
np.searchsorted(arr, 25)
# Output: 2 (25 should go before 30)

# Use when: You're inserting into a sorted array or doing binary search-like tasks.

np.int64(2)

In [ ]:

# ⚡ np.partition()

# Performs a partial sort: places the kth smallest item in its correct position, with smaller ones before and larger ones after, but doesn't fully sort.
# Example:

arr = np.array([7, 2, 9, 1, 6])
np.partition(arr, 2)
# Output: [2, 1, 6, 9, 7] (3 smallest elements on left)

array([1, 2, 6, 7, 9])